name: CloudHub Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build And Deploy to CloudHub
      env:
        ID: ${{ secrets.CONNECTED_APP_CLIENTID }}
        SECRET: ${{ secrets.CONNECTED_APP_CLIENTSECRETS }}
        MULE_VERSION: ${{ secrets.MULE_VERSION }}
        
      run: mvn clean deploy -DmuleDeploy 
       -DmuleVersion=$MULE_VERSION 
       -Dclient.id=$ID 
       -Dclient.secret=$SECRET --file pom.xml 
